In \[1\]:

    name = "   data science!789   "

### 1<a href="#1" class="anchor-link">¶</a>

In \[2\]:

    name = "   data science!789   "

In \[3\]:

    name.strip()

Out\[3\]:

    'data science!789'

### 2<a href="#2" class="anchor-link">¶</a>

In \[11\]:

    name.lower()

Out\[11\]:

    '   data science!789   '

### 3<a href="#3" class="anchor-link">¶</a>

In \[ \]:

    a = name.split('!')[0]

In \[ \]:

    b= name.split( '!')[1]

In \[10\]:

    a+b

Out\[10\]:

    '   data science789   '

#### 4<a href="#4" class="anchor-link">¶</a>

In \[12\]:

    x= name.capitalize()
    x

Out\[12\]:

    '   data science!789   '

### 5<a href="#5" class="anchor-link">¶</a>

In \[13\]:

    y=name.replace("science","analyst")
    y

Out\[13\]:

    '   data analyst!789   '

###### 6<a href="#6" class="anchor-link">¶</a>

In \[14\]:

    name.isalnum()

Out\[14\]:

    False

In \[15\]:

    name.isalpha()

Out\[15\]:

    False

In \[17\]:

    name.isascii()

Out\[17\]:

    True

### 7<a href="#7" class="anchor-link">¶</a>

In \[18\]:

    name

Out\[18\]:

    '   data science!789   '

In \[22\]:

    name.split()[0]

Out\[22\]:

    'data'

In \[24\]:

    name[3:7]

Out\[24\]:

    'data'

In \[ \]: